---
language: ruby
rvm: 3.0.0
sudo: false
cache: bundler
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
env:
- TASK='jekyll:check'
- TASK='jekyll:check_external_links'
matrix:
  fast_finish: true
  allow_failures:
  - env: TASK='jekyll:check_external_links'
script: bundle exec rake $TASK
before_install:
- gem update --system
- gem install bundler
